[package]
name = "i2pr-tc-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1"
i2pr-tc-core = { path = "../crates/i2pr-tc-core" }
i2pr-tc-storage = { path = "../crates/i2pr-tc-storage" }
i2pr-tc-i2p = { path = "../crates/i2pr-tc-i2p" }

[[bin]]
name = "bencode"
path = "fuzz_targets/bencode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "metainfo"
path = "fuzz_targets/metainfo.rs"
test = false
doc = false
bench = false

[[bin]]
name = "peer_wire"
path = "fuzz_targets/peer_wire.rs"
test = false
doc = false
bench = false

[[bin]]
name = "extension"
path = "fuzz_targets/extension.rs"
test = false
doc = false
bench = false

[[bin]]
name = "resume"
path = "fuzz_targets/resume.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sam"
path = "fuzz_targets/sam.rs"
test = false
doc = false
bench = false
